pipeline {
    agent {
        docker {
            image 'python:3.10'
        }
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Run avg.py') {
            steps {
               sh 'python version2/app/avg.py'
            }
        }
    }
}
